spring.application.name=MovieTheatreManagementSystem
spring.datasource.url=jdbc:mysql://root:mmxpEazoyWyJMeXOurIPqquYtFFEbRxm@ballast.proxy.rlwy.net:20305/railway
spring.datasource.username=root
spring.datasource.password=mmxpEazoyWyJMeXOurIPqquYtFFEbRxm
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

