spring.application.name=MovieTheatreManagementSystem

# S? d?ng H2 in-memory
spring.datasource.url=jdbc:h2:mem:movie_db;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# T?o b?ng t? entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# B?t console H2 (tu? ch?n)
spring.h2.console.enabled=true
spring.h2.console.path=/h2
