spring.application.name=MovieTheatreManagementSystem
spring.datasource.url=jdbc:mysql://localhost:3306/movietheatredb
spring.datasource.username=root
spring.datasource.password=Grooming4life
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=DEBUG
logging.level.org.springframework=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phongvnk@gmail.com
spring.mail.password=bslv oyjs wotx ntqx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true