spring.datasource.url=jdbc:mysql://localhost:3305/movietheatredb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Thiết lập dialect để Hibernate không phải dò metadata
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG

# dùng account cố định thay cho random password của Spring
spring.security.user.name=demoUser
spring.security.user.password=demoPass